format = "$directory$cmd_duration$git_branch$git_status$status"
add_newline = false

[status]
style = "bold red"
symbol = "✖"
format = '[\[$symbol$common_meaning$signal_name$maybe_int\]]($style) '
map_symbol = true
disabled = false

[git_status]
style = "yellow"
untracked= ">"
format = '[$all_status$ahead_behind]($style) '

[git_branch]
format = "[$symbol$branch]($style)"
